from enum import Enum


class ExitCode(Enum):
    EXIT_SUCCESS = 0
    WRONG_OPTION = 10
    OPEN_INPUT_FILE_ERROR = 11
    OPEN_OUTPUT_FILE_ERROR = 12
    WRONG_XML_FORMAT = 31
    WRONG_XML_STRUCTURE = 32
    INTERN_ERROR = 99
